# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=255)),
                ('marketing_title', models.CharField(blank=True, max_length=255)),
                ('editorial_title', models.CharField(blank=True, max_length=255)),
                ('date_submitted', models.DateField(default=datetime.date.today, verbose_name='date submitted')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ON_OFFER', 'On offer'), ('LIVE', 'Live'), ('COMMITTED', 'Success'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='ON_OFFER', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('length', models.PositiveSmallIntegerField(blank=True, help_text='How many weeks would this last?', null=True)),
                ('lead_time', models.PositiveSmallIntegerField(blank=True, help_text='How many weeks of advance notice does this require?', null=True)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Client')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea')),
            ],
            options={
                'verbose_name_plural': 'pitches',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Platform'),
        ),
    ]
