# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('ON_OFFER', 'On offer'), ('LIVE', 'Live'), ('COMMITTED', 'Committed'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='ON_OFFER', max_length=15),
        ),
    ]
