# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20171015_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='deliverables',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
