# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='sell_by',
            field=models.DateField(blank=True, null=True, verbose_name='sell_by'),
        ),
    ]
