# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_pitch_sell_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('ideas', models.ManyToManyField(blank=True, null=True, related_name='gdocs', related_query_name='gdoc', to='ideas.Idea')),
            ],
        ),
    ]
