# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_gdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdoc',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='gdocs', related_query_name='gdoc', to='ideas.Idea'),
        ),
    ]
