# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20171024_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdoc',
            options={'verbose_name': 'Google Doc', 'verbose_name_plural': 'Google Docs'},
        ),
    ]
