# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_auto_20171027_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdoc',
            name='ideas',
        ),
        migrations.AddField(
            model_name='idea',
            name='gdocs',
            field=models.ManyToManyField(blank=True, related_name='gdocs', related_query_name='gdoc', to='ideas.GDoc'),
        ),
    ]
