# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_auto_20171114_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='design',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('DELUXE', 'Deluxe'), ('CUSTOM', 'Custom')], default='BASIC', max_length=15),
        ),
        migrations.AddField(
            model_name='idea',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
