# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_idea_workday_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Not yet approved'), ('ON_OFFER', 'On offer'), ('TENTATIVE', 'Tentative'), ('LIVE', 'Live'), ('COMMITTED', 'Committed'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='ON_OFFER', max_length=15),
        ),
    ]
