# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_auto_20171130_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Not yet pitched'), ('POSSIBLE', 'Under consideration'), ('LIKELY', 'Likely to succeed'), ('ALMOST', 'Very likely to succeed'), ('SUCCESS', 'Pitch succeeded'), ('UNLIKELY', 'Long shot'), ('DEAD', 'No go')], default='DRAFT', max_length=15),
        ),
    ]
