# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0018_auto_20171219_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ideas',
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tag', to='ideas.Tag'),
        ),
    ]
