# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0019_auto_20171219_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EL', 'Editorial Lead'), ('SL', 'Sales Lead'), ('PL', 'Product Lead'), ('ML', 'Marketing Lead'), ('S', 'Stakeholder')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='gdocs',
            field=models.ManyToManyField(blank=True, related_name='ideas', related_query_name='idea', to='ideas.GDoc'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ideas', related_query_name='idea', to='ideas.Tag'),
        ),
        migrations.AddField(
            model_name='role',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='stakeholders',
            field=models.ManyToManyField(through='ideas.Role', to=settings.AUTH_USER_MODEL),
        ),
    ]
