# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0020_auto_20171220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('EL', 'Editorial Lead'), ('SL', 'Sales Lead'), ('PL', 'Product Lead'), ('ML', 'Marketing Lead'), ('S', 'Stakeholder')], default='S', max_length=3),
        ),
    ]
