# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0023_auto_20180102_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('long_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_sort_order', models.CharField(blank=True, default='start_date', max_length=255)),
                ('visible_to_sales', models.BooleanField(default=True)),
                ('visible_to_marketing', models.BooleanField(default=True)),
                ('visible_to_product', models.BooleanField(default=True)),
                ('visible_to_editorial', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='short_title',
            field=models.CharField(max_length=255, unique_for_year=models.DateField(default=datetime.date.today, verbose_name='date submitted')),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Not yet approved'), ('ON_OFFER', 'Available to pitch'), ('TENTATIVE', 'Still tentative'), ('COMMITTED', 'Committed but not yet scheduled'), ('SCHEDULED', 'Committed and scheduled'), ('LIVE', 'Currently active'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='ON_OFFER', max_length=15),
        ),
    ]
