# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0024_auto_20180105_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='short_title',
            field=models.CharField(max_length=255, unique_for_year='date_submitted'),
        ),
    ]
