# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0025_auto_20180105_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='ideas',
            field=models.ManyToManyField(related_name='pitches', related_query_name='pitch', to='ideas.Idea'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_idea', to='ideas.Idea'),
        ),
    ]
