# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 13:07
from __future__ import unicode_literals

from django.db import models, migrations

def forward(apps, schema_editor):
    Pitch = apps.get_model('ideas', 'Pitch')
    for pitch in Pitch.objects.all():
        pitch.ideas.add(pitch.idea)

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0026_auto_20180420_1305'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
