# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0027_auto_20180420_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gdoc',
            options={'verbose_name': 'Related URL', 'verbose_name_plural': 'Related URLs'},
        ),
        migrations.AlterField(
            model_name='pitch',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='date pitched'),
        ),
        migrations.AddField(
            model_name='pitchmeta',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Pitch'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='temp',
            field=models.ManyToManyField(through='ideas.PitchMeta', to='ideas.Idea'),
        ),
    ]
