# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0029_auto_20180423_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='ideas',
        ),
        migrations.AlterField(
            model_name='pitch',
            name='temp',
            field=models.ManyToManyField(related_name='pitches', related_query_name='pitch', through='ideas.PitchMeta', to='ideas.Idea'),
        ),
    ]
