# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0030_auto_20180424_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitch',
            old_name='temp',
            new_name='ideas',
        ),
    ]
