# Generated by Django 2.0.4 on 2018-04-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0031_auto_20180424_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PitchMeta',
            new_name='IdeaPitched',
        ),
        migrations.AlterModelOptions(
            name='ideapitched',
            options={'verbose_name': 'idea pitched', 'verbose_name_plural': 'ideas pitched'},
        ),
    ]
