# Generated by Django 2.0.7 on 2018-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0033_auto_20180725_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
    ]
