# Generated by Django 2.0.7 on 2018-10-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0034_idea_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('must_include', models.BooleanField(default=True)),
                ('committed', models.BooleanField(default=False)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_deliverables', related_query_name='key_deliverable', to='ideas.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='EndDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('major', models.BooleanField(default=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_end_date', related_query_name='new_end_date', to='ideas.Idea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdeaDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('major', models.BooleanField(default=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', related_query_name='key_dates', to='ideas.Idea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('major', models.BooleanField(default=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_start_date', related_query_name='new_start_date', to='ideas.Idea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
