# Generated by Django 2.0.7 on 2018-10-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0035_deliverable_enddate_ideadate_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enddate',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='startdate',
            name='short_desc',
        ),
    ]
