# Generated by Django 2.0.7 on 2018-10-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0036_auto_20181001_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enddate',
            options={'verbose_name_plural': 'End date'},
        ),
        migrations.AlterModelOptions(
            name='ideadate',
            options={'verbose_name': 'Key date', 'verbose_name_plural': 'Other key dates'},
        ),
        migrations.AlterModelOptions(
            name='startdate',
            options={'verbose_name_plural': 'Start date'},
        ),
        migrations.AddField(
            model_name='enddate',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideadate',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startdate',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ideadate',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_date', related_query_name='key_dates', to='ideas.Idea'),
        ),
    ]
