# Generated by Django 2.0.7 on 2018-10-01 18:52

from django.db import migrations

def generate_dates(apps, schema_editor):
    # We can't import the Idea model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    
    Idea = apps.get_model('ideas', 'Idea')
    StartDate = apps.get_model('ideas', 'StartDate')
    EndDate = apps.get_model('ideas', 'EndDate')
    for idea in Idea.objects.all():
        if idea.start_date:
            sd = idea.start_date
            std = StartDate.objects.create(idea=idea,date=sd)
        if idea.end_date:
            ed = idea.end_date
            end = EndDate.objects.create(idea=idea,date=ed)

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0037_auto_20181001_1840'),
    ]

    operations = [
        migrations.RunPython(generate_dates),
    ]
