# Generated by Django 2.0.7 on 2018-10-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0038_auto_20181001_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='creative_brief',
            field=models.URLField(blank=True, null=True),
        ),
    ]
