# Generated by Django 2.0.7 on 2018-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0039_idea_creative_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creative_brief',
            field=models.URLField(blank=True, help_text='This should be the URL of a Google Doc', null=True, verbose_name='creative brief URL'),
        ),
    ]
